name: Build & Deploy
on:
  push:
    branches:
      - main
      - chore/fix-build-ci-job

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Setup Tinygo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: "0.30.0"
      - name: Setup Templ
        shell: bash
        run: go install github.com/a-h/templ/cmd/templ@v0.2.501
      - name: Build & Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          preCommands: templ generate
